---
title: "RWorksheet_Marquez#3a"
author: "Kurt Sayro D. Marquez"
date: "2024-10-11"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# USING VECTORS
```{r}
LETTERS
```
```{r}
letters
```
#a. 
```{r}
firstlet <- LETTERS[1:11]
firstlet
```
#b. 
```{r}
oddlet <- LETTERS[seq(1, 26, by = 2)]
oddlet
```
#c. 
```{r}
vowels <- LETTERS[LETTERS %in% c("A", "E", "I", "O", "U")]
vowels
```
#d. 
```{r}
lastlet <- tail(letters, 5)
lastlet
```
#e. 
```{r}
betweenlet <- letters[15:24]
```
#2.
#a
```{r}
city <- c("Tuguegarao City", "Manila", "Iloilo City", "Tacloban", "Samal Island", "Davao City")
```
#b
```{r}
temp <- c(42, 39, 34, 34, 30, 27)
```
#c
```{r}
CityTemp <- data.frame(city, temp)
CityTemp

```
#d. 
```{r}
names(CityTemp) <- c("City", "Temperature")
CityTemp
```
#e.
```{r}
str(CityTemp)
```
#f. 
```{r}
CityTemp[3:4 ,]
```
#g.
```{r}
CityTemp[1 ,]
CityTemp[6 ,]
```
# USING MATRICES
#2. 
#a.
```{r}
matrix1 <- matrix(c(1,2,3,4,5,6,7,8,11,12,13,14), ncol = 4, nrow= 3)
matrix1
```
#b.
```{r}
multiplied <- matrix1 * 2
multiplied
```
#c. 
```{r}
matrix1[, 2]
```
#d.
```{r}
multiplied[1:2, 3:4]
```
#e.
```{r}
multiplied[3, 2:3]
```
#f
```{r}
multiplied[, 4]
```
#g.
```{r}
rownames(multiplied) <- c("isa","dalawa","tatlo")

colnames(multiplied) <- c("uno", "dos", "tres", "quatro")
multiplied
```
#h.
```{r}
dim(multiplied) <- c(6, 2)
multiplied
```
# USING ARRAYS
#3
#a.
```{r}
array1 <- array(c(1, 2, 3, 6, 7, 8, 9, 0, 3, 4, 5, 1), c(2,4,3))
array1
```
#b. the array has 3 dimensions
#c.
```{r}
dimnames(array1) <- list(c("a", "b"), c("A", "B", "C", "D"), c("1st-Dimensional Array", "2nd-Dimensional Array", "3rd-Dimensional Array"))
array1

```