---
title: "RWorksheet_Marquez#3b"
author: "Kurt Sayro D. Marquez"
date: "2024-10-14"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
#1.
#a.
```{r}
table1 <- data.frame(Respondent = c(1:20),
                     Sex = c(2,2,1,2,2,2,2,2,2,2,1,2,2,2,2,2,2,2,1,2),
                     FathersOccupation = c(1,3,3,3,1,2,3,1,1,1,3,2,1,3,3,1,3,1,2,1),
                     PersonsAtHome = c(5,7,3,8,5,9,6,7,8,4,7,5,4,7,8,8,3,11,7,6),
                     SiblingsAtSchool = c(6,4,4,1,2,1,5,3,1,2,3,2,5,5,2,1,2,5,3,2),
                     TypesOfHouses = c(1,2,3,1,1,3,3,1,2,3,2,3,2,2,3,3,3,3,3,2))
table1
```
#legend: Male=1  Female=2 Farmer=1 Driver=2 Others=3 Wood=1 Semi-Concrete=2 Concrete=3
#b.
```{r}
summary(table1)
```

#c. No, the mean is 2.95

#d.
```{r}
table1[1:2,]
```
#e.
```{r}
table1[c(3,5), c(2,4)]

```
#f.
```{r}
types_houses <- table1$TypesOfHouses
types_houses
```
#g.
```{r}
MaleFarmers <- subset(table1, Sex == 1 & FathersOccupation == 1)
MaleFarmers
```
#h.
```{r}
Female_Siblings <- subset(table1, Sex == 2 & SiblingsAtSchool >= 5)
Female_Siblings
```
#2.
```{r}
df = data.frame(Ints=integer(),

Doubles=double(), Characters=character(),
Logicals=logical(),
Factors=factor(),
stringsAsFactors=FALSE)

print("Structure of the empty dataframe:")
print(str(df))
```
#a. It displays the data type of the object
#3.
#a.
```{r}
HouseData <- read.csv("/cloud/project/RWorkSheet_Marquez#3b/HouseholdData.csv")
HouseData
```
#b.
```{r}
HouseData$Sex <- factor(HouseData$Sex, levels = c("Male", "Female"), labels = c(1,2))
HouseData
```
#c.
```{r}
HouseData$Types.of.Houses <- factor(HouseData$Types.of.Houses, levels = c("Wood", "Congrete", "Semi-congrete"), labels = c(1,2,3))
HouseData
```
#d. 
```{r}
HouseData$Fathers.Occupation <- factor(HouseData$Fathers.Occupation, levels = c(1,2,3), label = c("Farmer", "Driver", "Others"))
HouseData   
```
#e.
```{r}
Female_DriverDad <- subset(HouseData, Sex == 2 & Fathers.Occupation == "Driver")
Female_DriverDad
```
#f.
```{r}
manysibs <- subset(HouseData, Respondents & Siblings.at.School >= 5)
manysibs
```
#4. The graph represents the data of Sentiments of Tweets Per Day in the month of July. It shows the positve, neutral, and negative tweets per day.

```{r}
data <- data.frame(
  Date = rep(c("July 14, 2020", "July 15, 2020", "July 17, 2020", "July 18, 2020", "July 20, 2020", "July 21, 2020"), each = 3),
  Sentiment = rep(c("Negative", "Neutral", "Positive"), times = 6),
  Count = c(2500, 1500, 2000, 4200, 3000, 3100, 
            2000, 1200, 1800, 3000, 2500, 2700, 
            2800, 2100, 2600, 1800, 1200, 2200))
data$Date <- factor(data$Date, levels = c("July 14, 2020", "July 15, 2020", "July 17, 2020", 
                                          "July 18, 2020", "July 20, 2020", "July 21, 2020"))
data$Date
```
